<a href="https://colab.research.google.com/github/Dolsen0/numpy-quick/blob/main/numpyQuickT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Populate Arrays with specific numbers

In [6]:
# create a one dimensional array:
oneDimensional = np.array([.02, .2, .14, .8, 2.3, 1])

print(oneDimensional)

# two dimensional array:

twoDimensional = np.array([[2.3, 4.5, 2.2], [2.3, 1.2, .04]])

print(twoDimensional)

[0.02 0.2  0.14 0.8  2.3  1.  ]
[[2.3  4.5  2.2 ]
 [2.3  1.2  0.04]]


Populate random numbers with numpy

In [11]:
#random integers
random_int = np.random.randint(low=10, high=100, size=(5))

print(random_int)

#random floats between 0 - 1
random_float = np.random.random([3])

print(random_float)


#random float between 2 - 3
random_float_two = random_float + 2

print(random_float_two)

[92 88 13 89 15]
[0.76092076 0.80615173 0.96082857]
[2.76092076 2.80615173 2.96082857]


Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:



*   Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
*   Assign 15 values to a NumPy array named label such that:







In [18]:
feature = np.arange(6, 21)

label = (3 * feature) + 4

print(feature)

print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.

In [24]:
noise = (np.random.random([15]) * 4) - 2

label = label + noise

print(noise)
print(label)

[-1.22480487 -1.52795034  1.57733023  0.09664167  0.76215654  1.98961781
  1.1351644   1.26226272 -0.53847523 -0.37418428  0.75712345  1.77005405
 -1.8668857  -1.84083081  1.60517412]
[21.66345546 23.61310964 31.25050676 30.30555923 33.11602085 40.40788112
 42.69035411 45.59728521 44.90551335 50.61737739 54.24516453 56.90795265
 57.53609787 60.36574878 63.77820266]
