<a href="https://colab.research.google.com/github/Dolsen0/numpy-quick/blob/main/numpyQuickT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Populate Arrays with specific numbers

In [6]:
# create a one dimensional array:
oneDimensional = np.array([.02, .2, .14, .8, 2.3, 1])

print(oneDimensional)

# two dimensional array:

twoDimensional = np.array([[2.3, 4.5, 2.2], [2.3, 1.2, .04]])

print(twoDimensional)

[0.02 0.2  0.14 0.8  2.3  1.  ]
[[2.3  4.5  2.2 ]
 [2.3  1.2  0.04]]


Populate random numbers with numpy

In [11]:
#random integers
random_int = np.random.randint(low=10, high=100, size=(5))

print(random_int)

#random floats between 0 - 1
random_float = np.random.random([3])

print(random_float)


#random float between 2 - 3
random_float_two = random_float + 2

print(random_float_two)

[92 88 13 89 15]
[0.76092076 0.80615173 0.96082857]
[2.76092076 2.80615173 2.96082857]


In [14]:
feature = np.arange(6, 21)

print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
