In [2]:
import numpy as np

Populate Arrays with specific numbers

In [6]:
# create a one dimensional array:
oneDimensional = np.array([.02, .2, .14, .8, 2.3, 1])

print(oneDimensional)

# two dimensional array:

twoDimensional = np.array([[2.3, 4.5, 2.2], [2.3, 1.2, .04]])

print(twoDimensional)

[0.02 0.2  0.14 0.8  2.3  1.  ]
[[2.3  4.5  2.2 ]
 [2.3  1.2  0.04]]


Populate random numbers with numpy

In [10]:
#random integers
random_int = np.random.randint(low=10, high=100, size=(5))

print(random_int)

#random floats between 0 - 1
random_float = np.random.random([3])

print(random_float)

#random float 

[20 15 88 57 50]
[0.32469931 0.50158094 0.00851929]
